---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://burtherman.github.io/hugo_gh_blog"
title: "Burt's Blog Template for GitHub Pages"
canonifyurls: true
theme: "Lanyon"
...
